--------------------------------------------------------
--  颇老捞 积己凳 - 老夸老-4岿-26-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FREE_BBS
--------------------------------------------------------

  CREATE TABLE "FREE"."FREE_BBS" 
   (	"BBS_IDX" NUMBER, 
	"USER_ID" VARCHAR2(20 BYTE), 
	"BBS_MAIN_KATEGORY" VARCHAR2(20 BYTE), 
	"BBS_MIDDLE_KATEGORY" VARCHAR2(20 BYTE), 
	"BBS_SUBJECT" VARCHAR2(50 BYTE), 
	"BBS_CONTENT" VARCHAR2(1000 BYTE), 
	"BBS_VIEWS" NUMBER, 
	"BBS_REG_DATE" DATE, 
	"BBS_UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FREE_BBS_COMMENT
--------------------------------------------------------

  CREATE TABLE "FREE"."FREE_BBS_COMMENT" 
   (	"COMMENT_IDX" NUMBER, 
	"BBS_IDX" NUMBER, 
	"USER_ID" VARCHAR2(20 BYTE), 
	"COMMENT_CONTENT" VARCHAR2(500 BYTE), 
	"COMMENT_REG_DATE" DATE, 
	"COMMENT_UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FREE_BBS_FILE
--------------------------------------------------------

  CREATE TABLE "FREE"."FREE_BBS_FILE" 
   (	"BBS_IDX" NUMBER, 
	"USER_ID" VARCHAR2(20 BYTE), 
	"BBS_FILE_PATH" VARCHAR2(20 BYTE), 
	"ORIGIN_NAME" VARCHAR2(100 BYTE), 
	"NEW_FILE_NAME" VARCHAR2(100 BYTE), 
	"FILE_TYPE" VARCHAR2(20 BYTE), 
	"FILE_SIZE" VARCHAR2(20 BYTE), 
	"FILE_DATETIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FREE_MYFREELANCER
--------------------------------------------------------

  CREATE TABLE "FREE"."FREE_MYFREELANCER" 
   (	"PROJECT_IDX" NUMBER, 
	"PROJECT_SUBJECT" VARCHAR2(20 BYTE), 
	"CLIENT_ID" VARCHAR2(20 BYTE), 
	"FREELANCER_ID" VARCHAR2(20 BYTE), 
	"PROJECT_STATUS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FREE_PORTFOLIO
--------------------------------------------------------

  CREATE TABLE "FREE"."FREE_PORTFOLIO" 
   (	"USER_ID" VARCHAR2(20 BYTE), 
	"PORTFOLIO_PATH" VARCHAR2(100 BYTE), 
	"ORIGINNAME" VARCHAR2(100 BYTE), 
	"FILE_TYPE" VARCHAR2(20 BYTE), 
	"FILE_SIZE" VARCHAR2(20 BYTE), 
	"FILE_DATATIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FREE_PROJECT
--------------------------------------------------------

  CREATE TABLE "FREE"."FREE_PROJECT" 
   (	"PROJECT_IDX" NUMBER, 
	"USER_ID" VARCHAR2(20 BYTE), 
	"PROJECT_MAIN_KATEGORY" VARCHAR2(50 BYTE), 
	"PROJECT_MIDDLE_KATEGORY" VARCHAR2(20 BYTE), 
	"PROJECT_WORKING_KIND" VARCHAR2(20 BYTE), 
	"PROJECT_SUBJECT" VARCHAR2(50 BYTE), 
	"PROJECT_CONTENT" VARCHAR2(1000 BYTE), 
	"PROJECT_START_DATE" DATE, 
	"PROJECT_END_DATE" DATE, 
	"PROJECT_ADDRESS" VARCHAR2(100 BYTE), 
	"PROJECT_BUDGET" NUMBER, 
	"PROJECT_BUDGET_COORDINATION" NUMBER, 
	"PROJECT_IMAGE_PATH" VARCHAR2(100 BYTE), 
	"PROJECT_STATUS" NUMBER, 
	"PROJECT_VIEWS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FREE_USER
--------------------------------------------------------

  CREATE TABLE "FREE"."FREE_USER" 
   (	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_PW" VARCHAR2(20 BYTE), 
	"USER_NAME" VARCHAR2(20 BYTE), 
	"USER_EMAIL" VARCHAR2(20 BYTE), 
	"USER_PHONE1" VARCHAR2(20 BYTE), 
	"USER_PHONE2" VARCHAR2(20 BYTE), 
	"USER_PHONE3" VARCHAR2(20 BYTE), 
	"USER_ADDRESS" VARCHAR2(100 BYTE), 
	"FREELANCER_ABOUT_ME" VARCHAR2(1000 BYTE), 
	"FREELANCER_MAIN_KATEGORY" VARCHAR2(20 BYTE), 
	"FREELANCER_MIDDEL_KATEGORY" VARCHAR2(20 BYTE), 
	"FREELANCER_SKILL" VARCHAR2(500 BYTE), 
	"FREELANCER_CAREER" NUMBER, 
	"FREELANCER_CERTIFICATE" VARCHAR2(100 BYTE), 
	"FREELANCER_IMAGE_PATH" VARCHAR2(100 BYTE), 
	"FREELANCER_PUBLIC" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into FREE.FREE_BBS
SET DEFINE OFF;
REM INSERTING into FREE.FREE_BBS_COMMENT
SET DEFINE OFF;
REM INSERTING into FREE.FREE_BBS_FILE
SET DEFINE OFF;
REM INSERTING into FREE.FREE_MYFREELANCER
SET DEFINE OFF;
REM INSERTING into FREE.FREE_PORTFOLIO
SET DEFINE OFF;
REM INSERTING into FREE.FREE_PROJECT
SET DEFINE OFF;
REM INSERTING into FREE.FREE_USER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index FREE_BBS_COMMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FREE"."FREE_BBS_COMMENT_PK" ON "FREE"."FREE_BBS_COMMENT" ("COMMENT_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FREE_BBS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FREE"."FREE_BBS_PK" ON "FREE"."FREE_BBS" ("BBS_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FREE_PROJECT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FREE"."FREE_PROJECT_PK" ON "FREE"."FREE_PROJECT" ("PROJECT_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FREE_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FREE"."FREE_USER_PK" ON "FREE"."FREE_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FREE_BBS
--------------------------------------------------------

  ALTER TABLE "FREE"."FREE_BBS" ADD CONSTRAINT "FREE_BBS_PK" PRIMARY KEY ("BBS_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FREE"."FREE_BBS" MODIFY ("BBS_IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FREE_BBS_COMMENT
--------------------------------------------------------

  ALTER TABLE "FREE"."FREE_BBS_COMMENT" ADD CONSTRAINT "FREE_BBS_COMMENT_PK" PRIMARY KEY ("COMMENT_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FREE"."FREE_BBS_COMMENT" MODIFY ("COMMENT_IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FREE_BBS_FILE
--------------------------------------------------------

  ALTER TABLE "FREE"."FREE_BBS_FILE" MODIFY ("BBS_IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FREE_PROJECT
--------------------------------------------------------

  ALTER TABLE "FREE"."FREE_PROJECT" ADD CONSTRAINT "FREE_PROJECT_PK" PRIMARY KEY ("PROJECT_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FREE"."FREE_PROJECT" MODIFY ("PROJECT_IDX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FREE_USER
--------------------------------------------------------

  ALTER TABLE "FREE"."FREE_USER" ADD CONSTRAINT "FREE_USER_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FREE"."FREE_USER" MODIFY ("FREELANCER_PUBLIC" NOT NULL ENABLE);
  ALTER TABLE "FREE"."FREE_USER" MODIFY ("FREELANCER_IMAGE_PATH" NOT NULL ENABLE);
  ALTER TABLE "FREE"."FREE_USER" MODIFY ("FREELANCER_SKILL" NOT NULL ENABLE);
  ALTER TABLE "FREE"."FREE_USER" MODIFY ("FREELANCER_MIDDEL_KATEGORY" NOT NULL ENABLE);
  ALTER TABLE "FREE"."FREE_USER" MODIFY ("FREELANCER_MAIN_KATEGORY" NOT NULL ENABLE);
  ALTER TABLE "FREE"."FREE_USER" MODIFY ("USER_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "FREE"."FREE_USER" MODIFY ("USER_PHONE3" NOT NULL ENABLE);
  ALTER TABLE "FREE"."FREE_USER" MODIFY ("USER_PHONE2" NOT NULL ENABLE);
  ALTER TABLE "FREE"."FREE_USER" MODIFY ("USER_PHONE1" NOT NULL ENABLE);
  ALTER TABLE "FREE"."FREE_USER" MODIFY ("USER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "FREE"."FREE_USER" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "FREE"."FREE_USER" MODIFY ("USER_PW" NOT NULL ENABLE);
  ALTER TABLE "FREE"."FREE_USER" MODIFY ("USER_ID" NOT NULL ENABLE);
